# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: postgres:13.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn -P test test

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: 54a222bf-7770-4cb0-913d-c5a86161d181

workflows:
  build-test-coverage:
    jobs:
      - build-and-test
      