CREATE TABLE FRIENDSHIPS (
    FRS_ID BIGSERIAL PRIMARY KEY,
	FRS_AUDIT_CD TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FRS_AUDIT_MD TIMESTAMP,
	FRS_AUDIT_RD TIMESTAMP,
	FRS_USER_ID BIGSERIAL REFERENCES USERS(USER_ID) NOT NULL,
	FRS_FRIEND_ID BIGSERIAL REFERENCES USERS(USER_ID) NOT NULL,
	FRS_STATUS VARCHAR(1) NOT NULL,
	UNIQUE(FRS_USER_ID, FRS_FRIEND_ID)
);
