CREATE TABLE USERS (
	USER_ID BIGSERIAL PRIMARY KEY,
	USER_AUDIT_CD TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USER_AUDIT_MD TIMESTAMP,
	USER_AUDIT_RD TIMESTAMP,
	USER_PASSWORD VARCHAR(72) NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_FIRST_NAME VARCHAR(25) NOT NULL,
	USER_LAST_NAME VARCHAR(25) NOT NULL,
	USER_BIRTH_DATE TIMESTAMP NOT NULL,
	USER_COUNTRY VARCHAR(30) NOT NULL,
	USER_GENDER VARCHAR(1) NOT NULL,
	USER_ACTIVATED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IDX_UQ_USER_EMAIL ON USERS(UPPER(USER_EMAIL));

CREATE TABLE ROLES (
    ROLE_ID BIGSERIAL PRIMARY KEY,
	ROLE_CODE VARCHAR(20) UNIQUE NOT NULL,
	ROLE_NAME VARCHAR(25) NOT NULL,
	ROLE_AUDIT_CD TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ROLE_AUDIT_MD TIMESTAMP,
	ROLE_AUDIT_RD TIMESTAMP
);

CREATE TABLE USERS_ROLES (
    UR_USER_ID BIGSERIAL REFERENCES USERS(USER_ID),
    UR_ROLE_ID BIGSERIAL REFERENCES ROLES(ROLE_ID),
    PRIMARY KEY (UR_USER_ID, UR_ROLE_ID)
);

INSERT INTO ROLES (ROLE_CODE, ROLE_NAME)
VALUES
    ('ROLE_USER', 'User'),
    ('ROLE_ADMIN', 'Administrator');
