CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	USER_AUDIT_CD TIMESTAMP NOT NULL,
	USER_AUDIT_MD TIMESTAMP,
	USER_AUDIT_RD TIMESTAMP,
	USER_LOGIN VARCHAR(50) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	USER_EMAIL VARCHAR(255) UNIQUE NOT NULL,
	USER_ENABLED BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ROLES (
	ROLE_ID SMALLSERIAL PRIMARY KEY,
	ROLE_AUDIT_CD TIMESTAMP NOT NULL,
	ROLE_AUDIT_MD TIMESTAMP,
	ROLE_AUDIT_RD TIMESTAMP,
	ROLE_CODE VARCHAR (50) UNIQUE NOT NULL,
	ROLE_NAME VARCHAR (50) NOT NULL,
);
