CREATE TABLE COMMENTS (
    COMM_ID BIGINT PRIMARY KEY,
	COMM_AUDIT_CD TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	COMM_AUDIT_MD TIMESTAMP,
	COMM_AUDIT_RD TIMESTAMP,
	COMM_VERSION BIGINT NOT NULL DEFAULT 0,
	COMM_USER_ID BIGINT REFERENCES USERS(USER_ID) NOT NULL,
	COMM_POST_ID BIGINT REFERENCES POSTS(POST_ID) NOT NULL,
	COMM_CONTENT VARCHAR(1000) NOT NULL
);

CREATE SEQUENCE SEQ_COMM_ID START 50 INCREMENT 50;
