CREATE TABLE FRIENDSHIPS (
    FRS_ID BIGINT PRIMARY KEY,
	FRS_AUDIT_CD TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FRS_AUDIT_MD TIMESTAMP,
	FRS_AUDIT_RD TIMESTAMP,
	FRS_USER_ID BIGINT REFERENCES USERS(USER_ID) NOT NULL,
	FRS_FRIEND_ID BIGINT REFERENCES USERS(USER_ID) NOT NULL,
	FRS_STATUS VARCHAR(1) NOT NULL,
	UNIQUE(FRS_USER_ID, FRS_FRIEND_ID)
);

CREATE SEQUENCE SEQ_FRS_ID START 100 INCREMENT 50;
